version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - postgres
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: first
    ports:
      - '5432:5432'
